apiVersion: v1
kind: Service
metadata:
  name: bnp-banking-app-service
spec:
  type: NodePort
  selector:
    app: bnp-api  # C'est ce lien qui permet de trouver les Pods !
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30005